#include<iostream>
using namespace std;
main(){
int Num_1;
int Num_2;
int Num_3;
int Num_4;
int Num_5;
int Num_6;
int Num_7;
int Num_8;
int Num_9;
int Num_10;
int Num_11;
int Num_12;
int Num_13;
int Num_14;
int Num_15;
int Final_result;
cout<< "Number 1: ";
cin>> Num_1;
cout<< "Number 2: ";
cin>> Num_2;
cout<< "Number 3: ";
cin>> Num_3;
cout<< "Number 4: ";
cin>> Num_4;
cout<< "Number 5: ";
cin>> Num_5;
cout<< "Number 6: ";
cin>> Num_6;
cout<< "Number 7: ";
cin>> Num_7;
cout<< "Number 8: ";
cin>> Num_8;
cout<< "Number 9: ";
cin>> Num_9;
cout<< "Number 10: ";
cin>> Num_10;
cout<< "Number 11: ";
cin>> Num_11;
cout<< "Number 12: ";
cin>> Num_12;
cout<< "Number 13: ";
cin>> Num_13;
cout<< "Number 14: ";
cin>> Num_14;
cout<< "Number 15: ";
cin>> Num_15;
int Addition=Num_1+Num_2+Num_3+Num_4+Num_5;
int Multiplies=Num_6*Num_7*Num_8*Num_9*Num_10;
int Subtract=Num_11-Num_12-Num_13-Num_14-Num_15;
int First_result=Addition+Multiplies;
int final_result=First_result-Subtract;
cout<< "The final result is: "<<final_result;
}